name: Daily Auto-Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create commit file [24f2003130@ds.study.iitm.ac.in]
      run: |
        echo "Daily commit: $(date)" >> auto-commit.txt

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add auto-commit.txt
        git commit -m "Auto-commit: $(date)"
        git push
